export const base_url = 'http://localhost:5000/api'
export const login_url = base_url+'/login'
export const signup_url = base_url+'/signup'
export const create_post_url = base_url+'/post'
export const upvote_url = base_url+'/upvote'
export const downvote_url = base_url+'/downvote'
export const get_posts_url = base_url+'/posts'
export const comment_url = base_url+'/comment'